### ISSUE TITLE
ERROR [preprocessor.babel]: EMFILE, too many open files

### ISSUE THREAD

**Issue by kmdavis** [babel/karma-babel-preprocessor#22]
I am getting the following error for each file that is being preprocessed

```
ERROR [preprocessor.babel]: EMFILE, too many open files '/path/to/file'
```

and the same for my `.babelrc`

**Comment by kmdavis** [comment]
I was able to get a stack trace:
```
Error: EMFILE, too many open files '/<redacted>/.babelrc'
  at Object.fs.openSync (fs.js:439:18)
  at Object.fs.readFileSync (fs.js:290:15)
  at OptionManager.addConfig (/<redacted>/node_modules/karma-babel-preprocessor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:210:35)
  at OptionManager.findConfigs (/<redacted>/node_modules/karma-babel-preprocessor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
  at OptionManager.init (/<redacted>/node_modules/karma-babel-preprocessor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
  at File.initOptions (/<redacted>/node_modules/karma-babel-preprocessor/node_modules/babel-core/lib/transformation/file/index.js:191:75)
  at new File (/<redacted>/node_modules/karma-babel-preprocessor/node_modules/babel-core/lib/transformation/file/index.js:122:22)
  at Pipeline.transform (/<redacted>/node_modules/karma-babel-preprocessor/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
  at preprocess (/<redacted>/node_modules/karma-babel-preprocessor/lib/index.js:21:29)
  at nextPreprocessor (/<redacted>/node_modules/karma/lib/preprocessor.js:57:28)
  at /<redacted>/node_modules/karma/lib/preprocessor.js:93:7
  at fs.js:272:14
  at /<redacted>/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:104:5
  at Object.oncomplete (fs.js:108:15)
```

**Comment by kmdavis** [comment]
and for what it's worth, I set my ulimit to 10k, but it still failed.

**Comment by kmdavis** [comment]
ok... I'm slightly blind here... the EMFILE was not being raised for each file -- it's only being raised for 2 specific files:

`/<redacted>/node_modules/babel-plugin-transform-es2015-modules-amd/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/node_modules/lodash/object/keys.js`
and
`.babelrc`

**Comment by kmdavis** [comment]
When I disable the `babel-plugin-transform-es2015-modules-amd` module, it blows up with the otherwise same error on `node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-types/node_modules/babel-traverse/node_modules/babylon/lib/util/whitespace.js`

**Comment by shuhei** [comment]
Would you mind giving more context like node version, npm version and package.json?

**Comment by kmdavis** [comment]
node: 0.10.40
npm: 1.4.28
in our package.json, I'm requiring version 6.0.x

I'm going to try updating our version of node ("try" because last time we tried, we ran into a 3rd party dependency that didn't support anything newer than node 0.10)

**Comment by kmdavis** [comment]
updated node to 5.3.0 and that error went away. got other issues, but I think they're my own

**Comment by phenomnomnominal** [comment]
I'm running into this too, on Windows. Tried a whole bunch of different node version, `0.12.*`, `4.*`, `5.*` no luck. 

```
17 01 2016 16:42:36.489:ERROR [preprocessor.babel]: EMFILE, too many open files '...\node_modules\babel-preset-es2015\index.js'
```

Any thoughts?

**Comment by shuhei** [comment]
@phenomnomnominal Hmm. How many files did you try to transpile with Babel?

**Comment by phenomnomnominal** [comment]
Quite a few, it's a fairly large project. The error seems to be coming from within Babel itself actually now that I've dug into it a bit more.

The error gets thrown by a `require` call deep inside the call to `babel.transform(...);`

**Comment by shuhei** [comment]
Ah, `require` calls. Did you try npm 3.x? With Node 5.x latest, what if:

```sh
npm install -g npm
rm -rf node_modules
npm install
```

**Comment by phenomnomnominal** [comment]
Tried that too, no success, but managed to get around it by making a few globs a bit less general. Thanks anyways.

**Comment by shuhei** [comment]
Glad to hear that it worked!
